spring:
  application:
    name: LOGIN
  datasource:
    url: jdbc:postgresql://localhost:5432/login
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  liquibase:
    change-log: classpath:/db/migrations/changelog.xml

  security:
    user:
      name: furkan
      password: aydin




